version: '3.9'

services:
    server:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        labels:
            - "traefik.http.routers.server.rule=Host(`arena.maximtresk.ru`)"
            - "traefik.port=80"
            - "traefik.docker.network=web"
            - "traefik.http.routers.server.entrypoints=websecure"
            - "traefik.http.routers.server.tls.certresolver=myresolver"
        depends_on:
            - app
        container_name: arena_server
        networks:
            - web
            - internal

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
            - ./_docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
        depends_on:
            - db
        container_name: arena_app
        networks:
            - web
            - internal

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: arena
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: arena_db
        networks:
            - internal
            - web

networks:
    web:
        external: true
    internal:
        external: false
